apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
        - name: juiceshop
          image: bkimminich/juice-shop:latest
          ports:
            - containerPort: 3000
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: juiceshop-secret
                  key: admin-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: juiceshop-secret
                  key: jwt-secret
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          resources: {}
